/*
 * THE SOURCE CODE AND ITS RELATED DOCUMENTATION IS PROVIDED "AS IS". INFINEON
 * TECHNOLOGIES MAKES NO OTHER WARRANTY OF ANY KIND,WHETHER EXPRESS,IMPLIED OR,
 * STATUTORY AND DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF MERCHANTABILITY,
 * SATISFACTORY QUALITY, NON INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE.
 *
 * THE SOURCE CODE AND DOCUMENTATION MAY INCLUDE ERRORS. INFINEON TECHNOLOGIES
 * RESERVES THE RIGHT TO INCORPORATE MODIFICATIONS TO THE SOURCE CODE IN LATER
 * REVISIONS OF IT, AND TO MAKE IMPROVEMENTS OR CHANGES IN THE DOCUMENTATION OR
 * THE PRODUCTS OR TECHNOLOGIES DESCRIBED THEREIN AT ANY TIME.
 *
 * INFINEON TECHNOLOGIES SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT OR
 * CONSEQUENTIAL DAMAGE OR LIABILITY ARISING FROM YOUR USE OF THE SOURCE CODE OR
 * ANY DOCUMENTATION, INCLUDING BUT NOT LIMITED TO, LOST REVENUES, DATA OR
 * PROFITS, DAMAGES OF ANY SPECIAL, INCIDENTAL OR CONSEQUENTIAL NATURE, PUNITIVE
 * DAMAGES, LOSS OF PROPERTY OR LOSS OF PROFITS ARISING OUT OF OR IN CONNECTION
 * WITH THIS AGREEMENT, OR BEING UNUSABLE, EVEN IF ADVISED OF THE POSSIBILITY OR
 * PROBABILITY OF SUCH DAMAGES AND WHETHER A CLAIM FOR SUCH DAMAGE IS BASED UPON
 * WARRANTY, CONTRACT, TORT, NEGLIGENCE OR OTHERWISE.
 *
 * (C)Copyright INFINEON TECHNOLOGIES All rights reserved
 */

package com.infineon.esim.lpa.ui.generic;

public enum ActionStatus {
    GETTING_EUICC_INFO_STARTED,
    GETTING_EUICC_INFO_FINISHED,
    REFRESHING_EUICC_LIST_STARTED,
    REFRESHING_EUICC_LIST_FINISHED,
    CONNECTING_INTERFACE_STARTED,
    CONNECTING_INTERFACE_CANCELLED,
    CONNECTING_INTERFACE_FINISHED,
    DISCONNECTING_INTERFACE_STARTED,
    DISCONNECTING_INTERFACE_FINISHED,
    OPENING_EUICC_CONNECTION_STARTED,
    OPENING_EUICC_CONNECTION_FINISHED,
    GET_PROFILE_LIST_STARTED,
    GET_PROFILE_LIST_FINISHED,
    ENABLE_PROFILE_STARTED,
    ENABLE_PROFILE_FINISHED,
    DISABLE_PROFILE_STARTED,
    DISABLE_PROFILE_FINISHED,
    DELETE_PROFILE_STARTED,
    DELETE_PROFILE_FINISHED,
    SET_NICKNAME_STARTED,
    SET_NICKNAME_FINISHED,
    AUTHENTICATE_DOWNLOAD_STARTED,
    AUTHENTICATE_DOWNLOAD_FINISHED,
    DOWNLOAD_PROFILE_STARTED,
    DOWNLOAD_PROFILE_FINISHED,
    CANCEL_SESSION_STARTED,
    CANCEL_SESSION_FINISHED,
    CLEAR_ALL_NOTIFICATIONS_STARTED,
    CLEAR_ALL_NOTIFICATIONS_FINISHED
}
