-keep class com.infineon.esim.lpa.core.es9plus.messages.** { *; }
-keep class com.infineon.esim.lpa.core.es9plus.messages.request.** { *; }
-keep class com.infineon.esim.lpa.core.es9plus.messages.response.** { *; }