name: autoCI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install required platform
        run: sdkmanager "platforms;android-33" "build-tools;33.0.2"

      - name: Add local.properties
        run: echo ‘sdk.dir=/usr/local/lib/android/sdk’ >> ${{ github.workspace }}/local.properties

      - name: Get short SHA
        run: echo "SHA7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - uses: ilharp/sign-android-release@nightly
        name: Sign app APK
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.JKS_B64 }}
          keyStorePassword: ${{ secrets.JKS_PASSWD }}
          keyAlias: ${{ secrets.JKS_ALIAS }}

      - name: Upload Packages
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: InfiLPA-${{ env.SHA7 }}
          path: ${{steps.sign_app.outputs.signedFile}}